### ISSUE TITLE
Directions are unclear?

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/badges-and-schedules#13]
The first two methods were easy enough to write, but `assign_rooms` gave me a lot of difficulty. I ended up asking Amanda for help who pointed me to the `each_with_index` method on Enumerator (not on Array). Since, according to her, that was the expected answer and it isn't on the Array class, the instructions should hint about the method's existence. The final `printer` method gave me trouble to get the test to pass since each string needed it's own `puts` command. After some trial and error running the tests, i figured out that I needed to loop over the returned array and individually `puts` each string, rather than `puts` the entire array, but I came very close to giving up on this lab.

@SophieDeBenedetto

**Comment by SophieDeBenedetto** [comment]
should be fixed with latest commit

**Comment by markedwardmurray** [comment]
:+1:
