### ISSUE TITLE
eq versus eq?

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/badges-and-schedules#16]
Bug Description from user: 

I was working on the assign_rooms method of the badges and schedules module and typed the following: def assign_rooms(attendees) room_assignments << attendees.each {|i| "Hello, " + i + "! You'll be assigned to room " + "1" + "!"} end I expected it not to pass the rspec test since the room number was not changing but I did it anyway to make sure the rest of my code was working like it should. To my surprise it passed the rspec test so I tried to figure out why. 

It looks like the rspec test is coded as follows: it 'should return a list of welcome messages and room assignments' do expect(assign_rooms(attendees)).to eq(room_assignments) but from what I read online it might be better to code it as: it 'should return a list of welcome messages and room assignments' do expect(assign_rooms(attendees)).to eq?(room_assignments) I guess eq? is a stricter equality matcher than just eq. 

I changed the rspec to eq? on my cloned copy and reran the test and it failed as expected so I assume the eq? caught the mistake and failed the test. I could be wrong though since I am still wicked new to this stuff.

**Comment by SophieDeBenedetto** [comment]
I'm closing this issue. tried to replicate with this person's code and my tests did not pass.
