### ISSUE TITLE
Tests for #batch_badge_creator and #assign_rooms methods not comprehensive enough

### ISSUE THREAD

**Issue by Seanhetzel** [learn-co-curriculum/badges-and-schedules#27]
The #batch_badge_creator and #assign_rooms methods can be passed with:
```
def batch_badge_creator(names_array)
  names_array.each do |name|
    name.replace("Hello, my name is #{name}.")
  end
end

def assign_rooms(names_array)
  room = 1
  names_array.each do |name|
    name.replace("Hello, #{name}! You'll be assigned to room #{room}!")
    room += 1
  end
end
```
However, I think this modifies the original array #names_array so the #printer method receives an incorrect array. This results in the #printer method outputting: 
```
Hello, Hello, my name is Edsger.! You'll be assigned to room 1!
``` 
Where `Hello, my name is Edsger.` should be just `Edsger`. We haven't learned about `.replace` yet so maybe it should just be stated not to use it in this lab.

**Comment by drakeltheryuujin** [comment]
Hi @Seanhetzel,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
