### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by Adamlatorraca** [learn-co-curriculum/badges-and-schedules#28]
Providing a list of attendees right above an instruction requiring you to use a more general array leads to unnecessary confusion. Yes, the instructions below don't ask for an array of those names, but for new coders it seems natural that you'd use that information because why else would it be provided,

note: I haven't finished the lab yet so maybe it becomes useful but from reading ahead I don't believe it is

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not appear right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
