### ISSUE TITLE
The testing expectations seem unclear

### ISSUE THREAD

**Issue by drewkeat** [learn-co-curriculum/badges-and-schedules#31]
describe '#printer' do

    # Question 4
    # The method `printer` should output first the results of the batch_badge_creator method and then of the assign_rooms method to the screen - this way you can output
    # the badges and room assignments one at a time.
    # To make this test pass, make sure you are iterating through your badges and room assignments lists.

    it 'should puts the list of badges and room_assignments' do
      badges_and_room_assignments.each_line do |line|
        # $stdout is a Ruby global varibale that represents the current standard output.
        # In this case, the standard output is your terminal screen. This test, then,
        # is checking to see whether or not your terminal screen receives the correct
        # printed output.
        expect($stdout).to receive(:puts).with(line.chomp)
      end
      printer(attendees)
    end

My tests failed until I eliminated the "badge" method from my code... though the instructions explicitly state that you need to iterate through badges AND room assignments...

**Comment by bal360** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it.

I recommend reaching out to [AAQ](https://help.learn.co/en/articles/493024-where-can-i-ask-a-question-about-a-lesson) so you can investigate this further with a technical coach to see what in your code might be allowing the tests to pass.

As always, thanks for contributing! 💙
